### ISSUE TITLE
support finding the Gemfile.lock in a subdirectory

### ISSUE THREAD

**Issue by travi** [codeclimate/codeclimate-bundler-audit#29]
While I understand it is not common for the Gemfile to be anywhere but in the root of the repository, I have a project where it is under the `test/` directory. In its current state, this audit is unable to find it and I get the following error:

```
/usr/src/app/lib/cc/engine/bundler_audit/analyzer.rb:16:in `run': No Gemfile.lock found. (CC::Engine::BundlerAudit::Analyzer::GemfileLockNotFound)
    from /usr/src/app/bin/bundler-audit:7:in `<main>'
```

Would it be possible to either scan subdirectories or enable a configuration so that the containing directory could be provided?

**Comment by pbrisbin** [comment]
Hi @travi , this is definitely something we have on the roadmap for this engine, but isn't possible at this time. I'll leave this issue open with the feature and help-wanted labels and report back if someone's able to implement it. Thanks.

**Comment by jclif** [comment]
This would definitely be beneficial to our project as well, which is making use of the monolithic approach to source control.

**Comment by dblandin** [comment]
Hey @jclif,

As of https://github.com/codeclimate/codeclimate-bundler-audit/pull/40 we now support an alternate path to a `Gemfile.lock` file:

```yaml
engines:
  bundler-audit:
    enabled: true
    path: test/Gemfile.lock
```

I'm going to close this issue for now, but let us know if you run into any issues!

**Comment by travi** [comment]
@dblandin i'm [still seeing](https://codeclimate.com/github/travi/dotfiles/builds/99) the following error after [updating my config](https://github.com/travi/dotfiles/blob/a0b91347e5c23689fe5a83991e6a2f0e62a64090/.codeclimate.yml#L9-L11):

```
/usr/src/app/lib/cc/engine/bundler_audit/analyzer.rb:18:in `run': No Gemfile.lock found. (CC::Engine::BundlerAudit::Analyzer::GemfileLockNotFound)
	from /usr/src/app/bin/bundler-audit:9:in `<main>'
```

has this update not been deployed yet?

**Comment by dblandin** [comment]
@travi Sorry about that!

I forgot the nested `config` key in my last example. The correct addition should be:

```yaml
engines:
  bundler-audit:
    enabled: true
    config:
      path: test/Gemfile.lock
```

**Comment by travi** [comment]
looks like that took care of it. thanks!
