### ISSUE TITLE
bundle-audit update?

### ISSUE THREAD

**Issue by kkumler** [codeclimate/codeclimate-bundler-audit#5]
As it stands now, I think `bundle-audit update` can only happen when a new image version is created. What can be done to allow the vulnerability database to be updated more often than when a new repo commit?

**Comment by GordonDiggs** [comment]
We're working on a way to provide more regular updates to the image. We use CircleCI to build the image and update bundler-audit [at build time](https://github.com/codeclimate/codeclimate-bundler-audit/blob/master/Dockerfile#L9), so we can do it without committing to the repo.
